[cr148][Android] Conflict on BraveTabCollectionTabModelImplBase.isTabModelRestored()
Upstream moved isTabModelRestored() into the TabGroupModelFilter
interface, which TabModel now extends, making the previously
private method in BraveTabCollectionTabModelImplBase conflict
with the now-public interface method.

Error message:
../../brave/android/java/org/chromium/chrome/browser/tabmodel/BraveTabCollectionTabModelImplBase.java:61: error: isTabModelRestored() in BraveTabCollectionTabModelImplBase cannot implement isTabModelRestored() in TabGroupModelFilter
    private boolean isTabModelRestored() {
                    ^
  attempting to assign weaker access privileges; was public

Chromium change:
https://source.chromium.org/chromium/chromium/src/+/401697a07af594e4420ef1f4998d13f43533874f

commit 401697a07af594e4420ef1f4998d13f43533874f
Author: Jingping Sun <jings@microsoft.com>
Date:   Fri Mar 27 10:23:32 2026 -0700

    [TabModel] Make TabModel extend TabGroupModelFilter

    As part of combining these interfaces this CL is the first step.

    * IncognitoTabGroupModelFilterImpl is inlined onto
      IncognitoTabModelImpl.
    * StubTabGroupModelFilterImpl is no longer required.
    * EmptyTabModel now has stub methods for TabGroupModelFilter.

    BYPASS_LARGE_CHANGE_WARNING: all stub methods

    Bug: 463685717, 476144237, 493519189
    Change-Id: Ia27c3a355f92da60cdb3c1e8ac9fabe892b49bc0
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7684470
    Reviewed-by: Calder Kitagawa <ckitagawa@chromium.org>
    Reviewed-by: Sky Malice <skym@chromium.org>
    Commit-Queue: Jingping Sun <jings@microsoft.com>
    Cr-Commit-Position: refs/heads/main@{#1606333}